### ISSUE TITLE
Register and Log In yield IndexErro

### ISSUE THREAD

**Issue by enriquemanuel** [stormpath/stormpath-flask-sample#4]
When trying to Log In with credentials created inside Stormpath it yields IndexError

```python
Traceback (most recent call last):
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/app.py", line 72, in register
    _user = stormpath_manager.application.accounts.create({
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/flask_stormpath.py", line 213, in application
    )[0]
  File "/Users/enriquemanuel/dev/stormpath-flask-sample/env/lib/python2.7/site-packages/stormpath/resources/base.py", line 349, in __getitem__
    return self.__dict__['items'][idx]
IndexError: list index out of range
```

Everything is installed and running correctly based on the bootstrap and also in the requirements.

**Comment by rdegges** [comment]
Hey @enriquemanuel, this is happening because your Application doesn't exist. Something wonky must have happened during the setup procedure.

You'll want to make sure your app exists properly, then try this again.
